version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: creditos      
    ports:
      - "5432:5432"              
    volumes:
      - ./data:/var/lib/postgresql/data 
      - ./initdb:/docker-entrypoint-initdb.d 

volumes:
  data:
  initdb:
